// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.models.extensions.*;
import com.microsoft.graph.models.generated.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.requests.extensions.*;
import com.microsoft.graph.options.*;
import com.microsoft.graph.serializer.*;

import java.util.Arrays;
import java.util.EnumSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Device Management Setting Instance Reference Request.
 */
public class DeviceManagementSettingInstanceReferenceRequest extends BaseRequest implements IDeviceManagementSettingInstanceReferenceRequest {

    /**
     * The request for the DeviceManagementSettingInstance
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public DeviceManagementSettingInstanceReferenceRequest(String requestUrl, IBaseClient client, java.util.List<? extends Option> requestOptions) {
        super(requestUrl, client, requestOptions, DeviceManagementSettingInstance.class);
    }

    public void delete(final ICallback<DeviceManagementSettingInstance> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    public DeviceManagementSettingInstance delete() throws ClientException {
       return send(HttpMethod.DELETE, null);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    public IDeviceManagementSettingInstanceReferenceRequest select(final String value) {
        getQueryOptions().add(new QueryOption("$select", value));
        return (DeviceManagementSettingInstanceReferenceRequest)this;
    }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    public IDeviceManagementSettingInstanceReferenceRequest expand(final String value) {
        getQueryOptions().add(new QueryOption("$expand", value));
        return (DeviceManagementSettingInstanceReferenceRequest)this;
    }
    /**
     * Puts the DeviceManagementSettingInstance
     *
     * @param srcDeviceManagementSettingInstance the DeviceManagementSettingInstance reference to PUT
     * @param callback the callback to be called after success or failure
     */
    public void put(DeviceManagementSettingInstance srcDeviceManagementSettingInstance, final ICallback<DeviceManagementSettingInstance> callback) {
        send(HttpMethod.PUT, callback, srcDeviceManagementSettingInstance);
    }

    /**
     * Puts the DeviceManagementSettingInstance
     *
     * @param srcDeviceManagementSettingInstance the DeviceManagementSettingInstance reference to PUT
     * @return the DeviceManagementSettingInstance
     * @throws ClientException an exception occurs if there was an error while the request was sent
     */
    public DeviceManagementSettingInstance put(DeviceManagementSettingInstance srcDeviceManagementSettingInstance) throws ClientException {
        return send(HttpMethod.PUT, srcDeviceManagementSettingInstance);
    }
}
